### ISSUE TITLE
[Bug] @pl.jit.host L3 dispatch breaks when the host orchestrator is renamed: CommBufferSpec.__init__() got an unexpected keyword argument 'tensors'

### ISSUE THREAD

**Issue by zhangqi-chen** [hw-native-sys/pypto#1678]
### Component

Runtime — JIT `@pl.jit.host` distributed dispatch (`distributed_runner.py` entry-function resolution)

### Description

Renaming the `@pl.jit.host` orchestrator function **deterministically** breaks end-to-end L3 dispatch (the path added by #1660). The same program runs fine when the host function is named `host_orch`, but fails at dispatch when it is renamed to `moe_ep_l3` (also `l3_moe_ep`, `moe_l3`) with:

```
TypeError: CommBufferSpec.__init__() got an unexpected keyword argument 'tensors'
```

The generated orchestration code is **byte-identical** between the two names (only the function symbol differs), so this is a runtime entry-resolution issue, not codegen. `distributed_runner.py` calls the entry as `entry_fn(orch, _args, config, tensors=tensors, callables=chip_cids, ...)`; with certain host names `entry_fn` ends up bound to the wrong callable, so the `tensors=` kwarg lands on `CommBufferSpec.__init__`.

### Steps to Reproduce

1. A `@pl.jit.host` host orchestrator `host_orch` that allocates HCCL windows and dispatches a `@pl.jit` chip orchestration **named `moe_ep`** per rank (`device=r`), run via `run_jit(fn=host_orch, compile_cfg=dict(distributed_config=DistributedConfig(device_ids=[0,1])))`. (Concrete case: dsv4 `models/deepseek/v4/moe_ep.py` in pypto-lib.)
2. Run on 2 NPUs → **PASS**.
3. Rename only the host function `host_orch` → `moe_ep_l3` (nothing else) → re-run → **FAIL** with the error above.

Names tested in a single env window (same pypto, same hardware): `host_orch` → PASS, immediately followed by `moe_ep_l3` → FAIL. Also `l3_moe_ep` and `moe_l3` → FAIL (same error).

### Expected Behavior

L3 dispatch succeeds regardless of the host orchestrator's Python function name — the generated code is identical, so the name must not affect runtime entry resolution.

### Actual Behavior

```
File ".../pypto/runtime/distributed_runner.py", line 347, in execute_distributed
    _dispatch(w, entry_fn, tensors, chip_cids, sub_ids, _make_call_config(dc), len(dc.device_ids))
File ".../pypto/runtime/distributed_runner.py", line 291, in _dispatch
    w.run(orch_fn)
File ".../pypto/runtime/distributed_runner.py", line 280, in orch_fn
    entry_fn(
TypeError: CommBufferSpec.__init__() got an unexpected keyword argument 'tensors'
```

### Git Commit ID

`71b557f7`

### NPU Kind

Ascend 910B

### Host Platform

Linux (aarch64)

### Additional Context

- The generated `orchestration/host_orch.py` for the passing (`host_orch`) and failing (`moe_ep_l3`) builds is byte-identical after normalizing the function name (`diff` is empty).
- The generated host entry is `def <name>(orch, _args, config, *, tensors, callables, sub_ids, _keep, world_size)` — it **does** accept `tensors` — and it constructs `CommBufferSpec(name=..., dtype="opaque", count=..., nbytes=...)`, which matches the installed `simpler.task_interface.CommBufferSpec.__init__(name, dtype, count, nbytes, load_from_host, store_to_host)`. No generated code passes `tensors=` to `CommBufferSpec`.
- So the `tensors=` reaching `CommBufferSpec` comes from `distributed_runner.py:280` calling `entry_fn(..., tensors=tensors, ...)` against the wrong resolved callable. The likely trigger is a name collision/ordering with the chip orchestration named `moe_ep` (the host dispatches it via `callables["moe_ep"]`); host names that pass (`host_orch`) vs fail (`moe_ep_l3` / `l3_moe_ep` / `moe_l3`) differ in how they relate to `moe_ep`.
- Surfaced while authoring the dsv4 EP MoE end-to-end as a `@pl.jit.host` kernel (hw-native-sys/pypto-lib#452). Workaround: name the host orchestrator `host_orch`.
