### ISSUE TITLE
[Pass Bug] Simplify (PR #1238) produces malformed IR for nested-pl.pipeline + if/else pattern

### ISSUE THREAD

**Issue by Hzfengsy** [hw-native-sys/pypto#1243]
### Pass Name

Simplify (`src/ir/transforms/simplify_pass.cpp`) — specifically the const-condition If folding and short-For folding/unrolling logic introduced in PR #1238 (`b79e8ece feat(ir): Fold constant-condition If and pure single-trip For in Simplify`).

### Description

After PR #1238 lands, Simplify produces malformed IR when it sees the nested-`pl.pipeline` + `if/else` pattern that AutoTileMatmulL0 emits (outer user-`pl.pipeline(stage=2)` over K chunks with `if kb == 0: pl.matmul else: pl.matmul_acc`, and AutoTileMatmulL0 K-tiles each per-chunk matmul into an inner 2-iter pipeline with another `if ko == 0` init/acc switch). The folded IR has three kinds of damage:

1. **Type-mismatched assignment** — the LHS is annotated as one tile type, the RHS produces a different type (different shape, dtype, and memory space).
2. **Reused SSA names across sibling branches** of an `if/else` without a phi.
3. **Undefined references** — uses of names that are not declared anywhere in the function body.

The downstream symptom is `ptoas compilation failed: error: use of undeclared SSA value name`, but ptoas is the messenger — the bug is upstream in Simplify producing invalid pypto IR.

Pre-PR #1238, the same source program hung at runtime (different bug, in ptoas's event-flag codegen). PR #1238 changed the failure mode but didn't fix the root cause; instead it introduced a new compile-time crash on the same trigger pattern.

### Git Commit ID

`5edbc4a19e7d21f1682aa819588aa57ee3698bd7` (upstream/main HEAD at time of report — the bug is in PR #1238 / `b79e8ece`).

Reproducing the bug also requires `AutoTileMatmulL0` (currently unmerged on my feature branch — happy to push if helpful). The bug is purely in Simplify; AutoTileMatmulL0 is just the trigger that produces an IR shape Simplify mishandles.

### Before IR (Input)

After AutoTileMatmulL0 fires, the IR fed into Simplify looks like (full dump in `~/pypto/qwen3_hang_repro/ir_15_after_AutoTileMatmulL0_post_rebase.py`):

```python
import pypto.language as pl

# User-level program that triggers the bug
@pl.program
class OuterPipeBF16:
    @pl.function(type=pl.FunctionType.Orchestration)
    def orchestrator(
        self,
        a: pl.Tensor[[16, 1024], pl.BF16],
        b: pl.Tensor[[1024, 256], pl.BF16],
        out_c: pl.Out[pl.Tensor[[16, 256], pl.FP32]],
    ) -> pl.Tensor[[16, 256], pl.FP32]:
        with pl.at(level=pl.Level.CORE_GROUP, name_hint="outer_pipe_matmul"):
            acc = pl.create_tensor([16, 256], dtype=pl.FP32)
            for kb in pl.pipeline(8, stage=2):  # NUM_CHUNKS=8
                k0 = kb * 128
                tile_a = a[:, k0 : k0 + 128]
                tile_b = b[k0 : k0 + 128, 0:256]
                if kb == 0:
                    acc = pl.matmul(tile_a, tile_b, out_dtype=pl.FP32)
                else:
                    acc = pl.matmul_acc(acc, tile_a, tile_b)
            out_c = pl.assemble(out_c, acc, [0, 0])
        return out_c
```

After AutoTileMatmulL0 K-tiles each per-chunk matmul, Simplify sees inner 2-trip `pl.pipeline(0, 128, 64, stage=2)` loops with `if ko == 0: tile.matmul else: tile.matmul_acc` inside each branch of the outer `if kb == 0` — exactly the trigger pattern.

### Expected IR (After Transformation)

Either (a) Simplify leaves the IR alone if it can't safely fold (preferred — less aggressive), or (b) it unrolls/folds while preserving SSA scoping, type annotations, and the producer/consumer chain. As a minimum, every name used must be defined in a dominating scope, types on each side of an assignment must match, and no name may be redeclared in a sibling branch without a phi.

### Actual IR or Error

```text
ptoas compilation failed:
loc("/tmp/pypto_test_matmul_outer_pipe_bf16_16x1024x256_chunks8_*/ptoas/outer_pipe_matmul.pto":53:212):
  error: use of undeclared SSA value name
Error: Failed to parse MLIR.
```

The malformed pypto IR Simplify produced (snippet from `ir_32_after_Simplify_post_rebase.py`, the pass dump right before codegen):

```python
for kb__idx_v0, (acc__iter_v1,) in pl.range(0, 8, 2, init_values=(acc__tile,)):
    ...
    if kb__idx_v0 == 0:
        ...
        acc__tile_l0_c_first: pl.Tile[[16, 256], pl.FP32, ..., pl.Mem.Acc] = pl.tile.matmul(...)  # OK in then
        ...
        acc__tile_l0_c_acc: pl.Tile[[16, 256], pl.FP32, ..., pl.Mem.Acc] = pl.tile.matmul_acc(acc__tile_l0_c_first, ..., ...)
        acc__phi_v5: pl.Tile[[16, 256], pl.FP32, ..., pl.Mem.Acc] = pl.yield_(acc__tile_l0_c_acc)
    else:
        # BUG 1: lhs is Acc/FP32/[16,256], rhs produces Left/BF16/[16,64].
        # Simplify substituted the wrong RHS during unrolling.
        acc__tile_l0_c_first: pl.Tile[[16, 256], pl.FP32, ..., pl.Mem.Acc] = pl.tile.extract(
            tile_a__tile, 0, 0, [16, 64], target_memory=pl.Mem.Left)

        acc__tile_l0_b_2: ... = pl.tile.extract(tile_b__tile, 0, 0, [64, 256], target_memory=pl.Mem.Right)
        acc__tile_l0_c_acc_1: pl.Tile[[16, 256], pl.FP32, ..., pl.Mem.Acc] = pl.tile.matmul_acc(
            acc__iter_v1, acc__tile_l0_c_first, acc__tile_l0_b_2)
        ...
        acc__phi_v5: pl.Tile[[16, 256], pl.FP32, ..., pl.Mem.Acc] = pl.yield_(acc__tile_l0_c_acc_2)

    # ... outer loop body continues OUTSIDE the if/else ...
    # BUG 2: acc__tile_l0_c is referenced but never declared anywhere in this function.
    acc__tile_l0_c_acc_3: pl.Tile[[16, 256], pl.FP32, ..., pl.Mem.Acc] = pl.tile.matmul_acc(
        acc__tile_l0_c, acc__tile_l0_a_3, acc__tile_l0_b_4)
```

When this IR is lowered to MLIR text, the undefined `acc__tile_l0_c` becomes `%4` and is referenced from the else-branch despite being declared (in the malformed lowering) inside a sibling then-branch — hence the ptoas parser error at `outer_pipe_matmul.pto:53:212`.

For comparison, with PR #1238 reverted the same source program produced structurally well-formed IR (no scoping/type issues) — the bug is regressed in by PR #1238 specifically.

### NPU Kind (if relevant)

N/A (not hardware-specific)

### Host Platform (if relevant)

N/A (not hardware-specific)

### Additional Context

**Reproducer artifacts** (saved at `~/pypto/qwen3_hang_repro/`):

- `repro.py` — standalone `@pl.program` (the OuterPipeBF16 above)
- `NOTES.txt` — full diagnostic write-up (pre- and post-rebase comparison)
- `ir_15_after_AutoTileMatmulL0_post_rebase.py` — IR fed into Simplify
- `ir_32_after_Simplify_post_rebase.py` — malformed IR Simplify produced
- `outer_pipe_matmul_post_rebase.pto` — the lowered MLIR ptoas rejects (line 53)
- `qwen3_up_proj_post_rebase.pto`, `qwen3_sv_matmul_post_rebase.pto` — same root cause surfacing in two qwen3_decode kernels (`'pto.textract' op expects indexCol + dst.cols <= src.cols` and `'pto.textract' op expects src and dst to have the same element type`)

**Reproduce as a system test** (after building the worktree with AutoTileMatmulL0):

```bash
# Remove the @pytest.mark.skip on test_matmul_outer_pipelined_bf16 first
pytest -v tests/st/runtime/test_matmul.py::TestMatmulOperations::test_matmul_outer_pipelined_bf16 \
  --platform=a2a3 --codegen-only
```

`--codegen-only` is enough — the bug is at compile time post-PR #1238, no NPU needed.

**Bisect window**: bug regressed in by `b79e8ece` (PR #1238). The previous Simplify behaviour did not produce malformed IR for this pattern, though it left a different downstream issue (ptoas runtime hang) — that earlier hang is documented separately and will likely also need fixing once Simplify is correct.

**Suggested triage**: PR #1238 needs a tighter check before unrolling/inlining a `pl.pipeline` body with internal `if/else` — either (i) skip the fold when the inner if's condition references the loop variable (so each unrolled iteration has different control flow), or (ii) make the substitution carry over typed RHS expressions and rename to avoid sibling-scope collisions. Adding a verifier-after-Simplify in debug builds would have caught this immediately.

**Comment by Hzfengsy** [comment]
Closing as not-an-upstream-issue.

After investigation, the bug is **not present in upstream main**. It is introduced by my local branch's commit `feat(ir): Land L0 tile.extract switch and MemoryReuse retargeter extension`, which:
- Adds a `RetypeApplier::VisitExpr_(IterArgPtr)` override and a `VisitStmt_(ForStmtPtr)` override in `src/ir/transforms/memory_reuse_pass.cpp` that build fresh `IterArg` objects via `std::make_shared<IterArg>(...)` without consulting `var_remap_`. Each call returns a distinct pointer, so a For's `iter_args_` and its body end up referencing two different IterArg objects with the same `name_hint` — a malformed-IR pattern that downstream passes (Simplify Fold B in particular) cannot rewrite consistently.
- Triggers a previously-latent var_remap_ branch-leak in Simplify's IfStmt/ForStmt visitors when the L0 tiling produces inner Fors with shared iter_arg names across sibling if/else branches.

In upstream main, `RetypeApplier` has no `VisitExpr_(IterArgPtr)` override at all (it falls through to `IRMutator`'s default, which already checks `var_remap_`), and no existing IR pattern triggers the Simplify branch-leak — every existing test (1145 transforms tests) passes both with and without the fix. PR #1238's Simplify Fold A/B is in main but has nothing to misbehave on without the L0 work that produces the trigger pattern.

I created this issue prematurely while diagnosing on my local L0 branch. Both fixes have been folded into the same commit on my branch, so the bug never reaches a clean upstream PR.

Two real upstream concerns *did* surface during the investigation, filed separately:
- #1244 — Printer should suffix-disambiguate distinct Var/IterArg pointers that share `name_hint` (would have made this diagnosable from the pass dump).
- #1245 — Strengthen `structural_equal` to bijection over uses + adopt in per-pass round-trip (would have caught it at the test layer).
