### PR TITLE
fix(runtime): resolve distributed host orch entry by marker, not name

### LINKED ISSUE #1678: [Bug] @pl.jit.host L3 dispatch breaks when the host orchestrator is renamed: CommBufferSpec.__init__() got an unexpected keyword argument 'tensors'
### Component

Runtime — JIT `@pl.jit.host` distributed dispatch (`distributed_runner.py` entry-function resolution)

### Description

Renaming the `@pl.jit.host` orchestrator function **deterministically** breaks end-to-end L3 dispatch (the path added by #1660). The same program runs fine when the host function is named `host_orch`, but fails at dispatch when it is renamed to `moe_ep_l3` (also `l3_moe_ep`, `moe_l3`) with:

```
TypeError: CommBufferSpec.__init__() got an unexpected keyword argument 'tensors'
```

The generated orchestration code is **byte-identical** between the two names (only the function symbol differs), so this is a runtime entry-resolution issue, not codegen. `distributed_runner.py` calls the entry as `entry_fn(orch, _args, config, tensors=tensors, callables=chip_cids, ...)`; with certain host names `entry_fn` ends up bound to the wrong callable, so the `tensors=` kwarg lands on `CommBufferSpec.__init__`.

### Steps to Reproduce

1. A `@pl.jit.host` host orchestrator `host_orch` that allocates HCCL windows and dispatches a `@pl.jit` chip orchestration **named `moe_ep`** per rank (`device=r`), run via `run_jit(fn=host_orch, compile_cfg=dict(distributed_config=DistributedConfig(device_ids=[0,1])))`. (Concrete case: dsv4 `models/deepseek/v4/moe_ep.py` in pypto-lib.)
2. Run on 2 NPUs → **PASS**.
3. Rename only the host function `host_orch` → `moe_ep_l3` (nothing else) → re-run → **FAIL** with the error above.

Names tested in a single env window (same pypto, same hardware): `host_orch` → PASS, immediately followed by `moe_ep_l3` → FAIL. Also `l3_moe_ep` and `moe_l3` → FAIL (same error).

### Expected Behavior

L3 dispatch succeeds regardless of the host orchestrator's Python function name — the generated code is identical, so the name must not affect runtime entry resolution.

### Actual Behavior

```
File ".../pypto/runtime/distributed_runner.py", line 347, in execute_distributed
    _dispatch(w, entry_fn, tensors, chip_cids, sub_ids, _make_call_config(dc), len(dc.device_ids))
File ".../pypto/runtime/distributed_runner.py", line 291, in _dispatch
    w.run(orch_fn)
File ".../pypto/runtime/distributed_runner.py", line 280, in orch_fn
    entry_fn(
TypeError: CommBufferSpec.__init__() got an unexpected keyword argument 'tensors'
```

### Git Commit ID

`71b557f7`

### NPU Kind

Ascend 910B

### Host Platform

Linux (aarch64)

### Additional Context

- The generated `orchestration/host_orch.py` for the passing (`host_orch`) and failing (`moe_ep_l3`) builds is byte-identical after normalizing the function name (`diff` is empty).
- The generated host entry is `def <name>(orch, _args, config, *, tensors, callables, sub_ids, _keep, world_size)` — it **does** accept `tensors` — and it constructs `CommBufferSpec(name=..., dtype="opaque", count=..., nbytes=...)`, which matches the installed `simpler.task_interface.CommBufferSpec.__init__(name, dtype, count, nbytes, load_from_host, store_to_host)`. No generated code passes `tensors=` to `CommBufferSpec`.
- So the `tensors=` reaching `CommBufferSpec` comes from `distributed_runner.py:280` calling `entry_fn(..., tensors=tensors, ...)` against the wrong resolved callable. The likely trigger is a name collision/ordering with the chip orchestration named `moe_ep` (the host dispatches it via `callables["moe_ep"]`); host names that pass (`host_orch`) vs fail (`moe_ep_l3` / `l3_moe_ep` / `moe_l3`) differ in how they relate to `moe_ep`.
- Surfaced while authoring the dsv4 EP MoE end-to-end as a `@pl.jit.host` kernel (hw-native-sys/pypto-lib#452). Workaround: name the host orchestrator `host_orch`.

### PR DESCRIPTION
**Pull request by luohuan19**
## Summary

Renaming the `@pl.jit.host` orchestrator function (e.g. `host_orch` → `moe_ep_l3`) deterministically broke L3 dispatch with:

```
TypeError: CommBufferSpec.__init__() got an unexpected keyword argument 'tensors'
```

The generated orchestration code is byte-identical except for the function symbol, so this was a **runtime entry-resolution** bug, not codegen output.

### Root cause

`distributed_runner._load_orch_entry` resolved the entry by **guessing the name**: it tried the attributes `("entry", "host_orch")`, then fell back to scanning `dir(module)` **alphabetically** for the first non-underscore callable. For any host name outside that hardcoded set, the alphabetical fallback bound to the imported `CommBufferSpec` class (uppercase sorts before the lowercase function name); `_dispatch` then called it with `tensors=...`, raising the error above.

### Fix — explicit codegen marker, name-independent resolution

- `DistributedCodegen` tags the emitted orchestrator/entry with a sentinel attribute (`<name>._pypto_distributed_entry = True`) via a new `EmitEntryMarker` helper.
- `_load_orch_entry` selects the unique module-level function carrying that marker, independent of its Python name, and raises a clear error if the module has zero or multiple markers.

Entry resolution is now fully decoupled from the user's host function name, while keeping the meaningful name in generated code and tracebacks. The marker string is a cross-layer contract kept in sync between the C++ codegen and the Python runtime (comments cross-reference each side).

## Testing

- [x] New codegen UT: a renamed host orchestrator emits the marker after its `def`.
- [x] New runtime UTs: `_load_orch_entry` resolves the marked function (never an imported class); zero/multiple markers raise.
- [x] `tests/ut/runtime/` + `tests/ut/codegen/` — 618 passed, 14 skipped.
- [x] `ruff` clean; C++ rebuild passes.

## Related Issues

Fixes #1678

### CODE REVIEW

File: python/pypto/runtime/distributed_runner.py [hunk 1]
```diff
@@ -144,19 +157,20 @@ def _load_orch_entry(output_dir: Path) -> tuple[Any, Any]:
...
-                entry_fn = obj
-                break
-    if entry_fn is None:
-        raise RuntimeError(f"No entry function found in {orch_path}")
+    entry_candidates = [
+        obj
+        for name in dir(orch_module)
+        if isinstance((obj := getattr(orch_module, name)), types.FunctionType)
+        and getattr(obj, _ENTRY_MARKER, False)
+    ]
```
[the remark this answers is not in the document]
Comment (luohuan19) [reply python/pypto/runtime/distributed_runner.py:166]: Fixed in `929605e5` — added `getattr(obj, "__module__", None) == orch_module.__name__` to the candidate filter so imported functions carrying the marker are excluded. Thanks!

**Review by lyfne123 — APPROVED** [review]
