### PR TITLE
perf(distributed): bound the all_to_all_v transfer by the runtime row count

### LINKED ISSUE #2524: all_to_all_v transfers full MAX_RECV capacity on the wire instead of the runtime row count
## Summary

`pld.tensor.all_to_all_v` always pushes the full compile-time `MAX_RECV` row block to every peer, regardless of how many rows that peer is actually being sent. On data-dependent exchanges with a skewed distribution — MoE dispatch being the motivating case — most of that traffic is padding the receiver immediately discards.

The backend has supported the fix since PTOAS v0.57. The pypto lowering was never updated to use it. This issue tracks that work.

## Current behaviour

`python/pypto/runtime/builtins/collectives/all_to_all_v/templates/kernel.cpp.in:118` states it directly:

> The TPUT **ALWAYS** transfers the full `max_recv`-row block, regardless of `rows` — this reproduces `LowerTensorAllToAllVRule` exactly (its `pld.tile.put` transfer_shape is the compile-time `{max_recv, SIZE}`, never gated by the runtime count). Rows beyond a sender's `rows` therefore **DO cross the interconnect** (as whatever bytes happen to be in that capacity slot of `input`); the receiver skips them via `recv_counts`.

`rows = min(send_counts[dest], max_recv)` **is** computed at runtime, but it is used only for the `TNOTIFY` that publishes `recv_counts` to the peer. It never bounds the TPUT itself.

Both rails behave this way: the HOST builtin kernel above, and `LowerTensorAllToAllVRule` on the InCore path.

### Cost

With `MAX_RECV` sized for the worst-case expert load, a rank sending 1 row to an underloaded expert still puts `MAX_RECV` rows on the wire. For `MAX_RECV = 32` that is 32× the necessary bytes to that peer. The waste scales with how skewed the routing is, i.e. it is worst exactly when MoE dispatch is most imbalanced.

## Why this is actionable now

The historical blocker was PTOAS rejecting `?`-dimensioned partition views on `pto.comm.tput`. **That constraint is gone**, verified against the pinned toolchain:

- `verifyCommGlobalLike` takes a `CommGlobalShapePolicy` (`StaticOnly` | `AllowDynamicPartitionView`) — PTOAS `lib/PTO/IR/PTO.cpp:4758`, `:4763`
- `TPutOp::verify()` (`:19960`) and `TGetOp::verify()` (`:19985`) both pass `AllowDynamicPartitionView` for `dst` and `src`
- PTOAS ships a positive lit test: `test/lit/pto/comm_p2p_dynamic_partition_emitc.pto` (`?x4096` through `tput` and `tget`, EmitC + native)

Reproducible check with the **pinned** `ptoas 0.57` from `toolchain/versions.env`:

```console
$ ptoas --version
ptoas 0.57
$ ptoas --pto-arch=a3 --pto-level=level3 comm_p2p_dynamic_partition_emitc.pto -o /dev/null
$ echo $?
0
```

Full `level3` lowering succeeds, so the EmitC `GlobalTensor` path handles dynamic extents too.

pypto also already has the required plumbing: `ValidateDynamicTransferChunking` (`src/ir/op/distributed/comm_op_utils.h:100`) supports a dynamic leading transfer dim, requiring only a static `chunk_rows` to bound the VEC staging tile. That is exactly the target shape — dynamic `[rows, SIZE]` transfer with a compact static stage.

> Note for anyone verifying: the `"positive static shape"` string still in `PTO.cpp` belongs to `verifyCommStagingTileLike` (`:4813`), which governs the **VEC staging tile** and must stay static. It is not the partition-view check. Grepping for it gives a false "still blocked" reading.

## The actual design decision

This is **not** a one-line change, and the current behaviour is deliberate. From the same kernel template, `kernel.cpp.in:124`:

> This is **intentional InCore/HOST parity**, not a shortcut: it keeps the two lowering paths bit-for-bit identical on the wire and avoids a second, functionally divergent all_to_all_v implementation.

So there are two viable directions, and picking one is the first task:

1. **Change both rails together** — update `LowerTensorAllToAllVRule` and the HOST builtin kernel in lockstep, preserving bit-for-bit wire parity. Higher cost, keeps the invariant.
2. **Let the rails diverge on the wire** — accept that HOST and InCore no longer produce identical traffic. Cheaper, but breaks a property the code currently maintains on purpose.

## Proposed work

- [ ] Decide between wire-parity-preserving vs. divergent (above)
- [ ] Emit a dynamic `[rows, SIZE]` transfer shape with a static `chunk_rows`-bounded staging tile
- [ ] Keep `recv_counts` semantics unchanged — receivers already skip invalid rows correctly
- [ ] ST covering a skewed `send_counts` (e.g. one peer 1 row, another `MAX_RECV`) asserting correctness
- [ ] Measure the bandwidth delta on NPU to confirm the win is real
- [ ] Fix the misleading comment at `src/ir/op/distributed/collective.cpp:638`, which calls `send_counts` "what makes the exchange genuinely variable-size rather than a padded transfer of the full MAX_RECV capacity" — true of the semantics, not of the wire

## Affected

| Op | Status |
|---|---|
| `all_to_all_v` | Transfers full `MAX_RECV` per peer instead of `send_counts[dest]` rows |
| `reduce_scatter` (future) | Would inherit the same pattern |
| `broadcast` (future) | Unaffected — sends the full buffer by definition |

## History

Supersedes #2213, which filed this as a PTOAS limitation. That analysis was correct when written but is now stale in every load-bearing detail: the PTOAS constraint was lifted, and its proposed Options A/B/C were all PTOAS-side asks that no longer apply. #2213 has a comment recording the full re-evaluation. This issue restates the problem as it exists today, on `main` (`e1ea278f`), with the work located in pypto.

### PR DESCRIPTION
**Pull request by georgebisbas**
> [!NOTE]
> **Ready for review.** The NPU bandwidth gate returned **GO on device counters** (see [NPU gate results](#npu-gate-results)); wall-clock in the shipped harness is below the noise floor (compile-dominated). All gate items are closed — see [Outstanding](#outstanding).

Closes #2524.

## Summary

`pld.tensor.all_to_all_v` pushed the full compile-time `MAX_RECV` row block to every peer regardless of how many rows it was actually sending, so on a skewed exchange (MoE dispatch being the motivating case) most of the traffic was padding the receiver immediately discarded.

`rows = min(send_counts[dest], MAX_RECV)` was **already** computed at runtime on both rails — it only ever fed the `TNOTIFY` that publishes `recv_counts`, never the transfer shape. The kernel template said so outright:

> The TPUT **ALWAYS** transfers the full `max_recv`-row block, regardless of `rows` […] Rows beyond a sender's `rows` therefore **DO cross the interconnect**.

The transfer shape is now the runtime `[rows, SIZE]` on both rails.

## Why this is possible now

This was historically blocked by PTOAS rejecting `?`-dimensioned partition views. That constraint is gone:

- `TPutOp::verify` / `TGetOp::verify` pass `CommGlobalShapePolicy::AllowDynamicPartitionView`
- the **pinned** `ptoas 0.57` lowers a `?x4096` partition view through full EmitC (`--pto-level=level3`, exit 0) — verified on the pinned wheel, not a newer PTOAS

**No `chunk_rows` attr is involved.** `ValidateDynamicTransferHasChunk` governs `pld.tensor.put`; this lowering emits `pld.tile.put`, which takes an explicit `[1, SIZE]` staging tile and validates through `ValidateStageFitsTransfer` — that one deliberately skips dynamic dims. `pld.tile.put` does not register a `chunk_rows` attr at all.

## Behaviour changes

Two, both intentional, both applied to the InCore and HOST rails **together** so the deliberate bit-for-bit wire parity between them is preserved:

1. **Rows past the transfer extent are no longer written.** Previously the full-capacity push filled them with the sender's surplus rows. Window memory is not *guaranteed* zeroed and can carry over within a process, so those bytes are now undefined rather than merely meaningless. `recv_counts` is what makes either correct, and always was — only code reading past `recv_counts` can tell the difference, and it was already reading data it had no claim to.
2. **A negative `send_counts[dest]` now publishes `recv_counts = 0`** instead of the negative value. The clamp became two-sided because `rows` now sizes a transfer, and the published count is that same clamped value.

The `rows > 0` guard on the InCore put wraps the `pld.tile.put` **only** — the count `TNOTIFY` stays unconditional, or a zero-row destination would read a stale `recv_counts`.

### Job 1 — window-overlap probe: **windows are distinct**

A probe with no collective (sentinel into window A, read never-written window B) gives **0/128 sentinel hits** — the two `alloc_window_buffer` calls do **not** share storage on NPU. Not an allocator defect.

Consequence for the 3 HOST ST failures seen on NPU (`test_host_all_to_all_v_skewed_counts[2-negative|one_and_full|zero_and_full]`, all at `rank=0 src=0`): the **self-slot padding assertion is unsound**, not an over-send. On `src == rank` the receiver's unwritten window rows already hold the sender's locally-staged data (window memory is not *guaranteed* zeroed and can carry over within a process), so the assertion cannot distinguish a real over-send from pre-existing staged data. `recv_counts` is correct on both rails for every case; `over_capacity` passes (no padding rows). **Open item:** skip `src == rank` in the padding loop of `test_l3_host_tensor_all_to_all_v.py` (with a comment).

### Job 2 — bandwidth (InCore rail): **GO on device counters**

Benchmark experiments: `tests/st/distributed/collectives/test_l3_tensor_all_to_all_v_intrinsic.py` (InCore rail), edited to `MAX_RECV = 32`, `SIZE = 64`, extreme `send_counts` (one peer **1 row**, the other **32**), P=2 on the free devices 4,5 — baseline `913a5b53` vs branch `eae3b463`. Two measurements per tree: wall-clock (`pytest --durations=10`, n=5, median) and device-side PMU (`enable_pmu=2`, per-task AIV exchange kernel: `pmu_total_cycles`, `mte2_busy_cycles`, `mte3_busy_cycles`). The HOST rail (same ST file and config) was the structural cross-check.

| metric | baseline `913a5b53` | branch `eae3b463` | Δ |
|---|---|---|---|
| wall-clock median (`pytest --durations`, n=5) | 9.25 s | 9.25 s | none — compile-dominated harness, below noise floor |
| exchange-kernel `pmu_total_cycles` (per-task PMU, clean rank; n=13 / n=7) | ≈75.9 K | ≈47.3 K | **−38 %** |
| `mte3_busy_cycles` (data-movement pipe) | ≈37.7 K | ≈17.1 K | **−55 %** |
| `mte2_busy_cycles` | ≈26.9 K | ≈19.6 K | −27 % |

The mte3 drop (~2.2×) tracks the payload ratio (64 → 33 rows = 52 %): the InCore `pld.tile.put` declared extent `[rows, SIZE]` **is honoured by the TPUT engine** — fewer bytes cross the wire. This answers the gate's core question ("does TPUT chunk identically regardless of the declared extent?") with **no**. HOST-rail cross-check: the generated exchange kernel is loop-bounded by the runtime count (`block_numel = rows64 * row_numel`, two-sided clamp), verified in the emitted code — structurally fewer TPUTs.

Wall-clock in the shipped harness is compile/dispatch-dominated (this runtime recompiles per dispatch) and cannot separate 16 KB vs 8 KB transfers; the win is at the kernel level and would surface in resident/steady-state dispatches (the MoE case).

## Testing

| Gate | Result |
|---|---|
| Full UT suite | 10409 passed, 13 skipped, 2 xfailed |
| `all_to_all_v` UTs | 7/7 (3 new, 1 repaired) |
| `tests/st/distributed/` (whole directory, sim) | 171 passed, 8 failed |
| Same 8 on unmodified base (sim) | **8 failed — identical IDs** |
| `tests/st/distributed/` (NPU, P=2) | **120 passed, 53 skipped**, plus 3 self-slot HOST assertions excluded as unsound on `src == rank` (Job 1; the `skip src == rank` follow-up landed in this PR) |
| InCore ST full file (NPU, P=2 + P=4, `MAX_RECV=32`) | **passes** (intermittent environmental P=4 scheduler-timeout flake: different test each full-file run, all pass in isolation on both trees) |
| `pre-commit` | green on all 8 changed files |

The 8 sim ST failures are pre-existing kernel-compilation errors in ring allreduce / broadcast / reduce_scatter (a template↔pto-isa mismatch in the sim image), identical on the unmodified base; they do **not** appear on NPU.

### New tests

- **UT regression lock** on the transfer shape. Nothing previously asserted it, so it could silently revert to a constant with every other test still green — correctness is unaffected either way, only the bytes on the wire change.
- **UTs** for the zero floor, and for the count notify sitting *outside* the `rows > 0` guard.
- **STs on both rails** covering `send_counts` of `0`, `1`, `MAX_RECV`, over-capacity and negative, at P=2 and P=4. Driving both rails with the same cases against the same golden is the wire-parity gate.

The ST payloads are salted per (case, rank-count). Window memory is not *guaranteed* zeroed and can carry over between tests in one process, so an unwritten row can otherwise hold the exact pattern an earlier test wrote — indistinguishable from a real over-send, and a false failure.

## Outstanding

- [x] **NPU bandwidth measurement (GO/NO-GO).** **GO** on device counters (Job 2 above): exchange kernel −38 % cycles, data-movement pipe −55 %, matching the payload ratio. Wall-clock below the noise floor of the shipped harness.
- [x] **NPU P=2 / P=4 correctness** for `all_to_all_v` on both rails. P=2 green; P=4 green in isolation (intermittent environmental scheduler-timeout flake in back-to-back full-file runs).
- [x] **HOST self-slot surplus-row check (Job 1).** The `skip src == rank` exclusion has landed in this PR (see [NPU gate results](#npu-gate-results)): the window-overlap probe showed the two windows are distinct, so on `src == rank` the assertion was comparing against locally-staged data, not an over-send. The InCore rail keeps the check and passes it on NPU.
- [x] **AI review feedback (2026-08-26).** Addressed: the InCore skew ST now reads the full receive window through a `window_out` probe so its bounded-transfer tail check is non-vacuous; the registered op description, lowering-rule header, and an in-test comment were updated to the runtime `[rows, SIZE]` contract. Related STs pass on sim (10/10 intrinsic, 10/10 HOST); `pre-commit` and `clang-tidy` clean.

### CODE REVIEW

**Comment by georgebisbas** [comment]
## NPU run 1: correctness ✅ (with one test correction) — measurement still outstanding

### What the hardware established

`a2a3`, `--device 12,13`, whole `tests/st/distributed` directory: **120 passed, 3 failed, 53 skipped**.

- **InCore rail fully green**, self slot included. This is the rail carrying the real risk — its transfer shape is a *declared extent*, so it depends on TPUT honouring it. The HOST rail's reduction is structural (a loop bound), so it was never in doubt.
- **`recv_counts` correct on both rails for every skew case** — the two-sided clamp and the zero floor work on hardware.

### The 3 failures were my test, not the change

All three were the HOST-rail surplus-row assertion at `rank=0 src=0` — the self-send slot.

They cannot be an over-send. For the zero and negative cases the clamped count is **0**, `recv_counts` confirmed 0, so:

```cpp
int64_t block_numel = rows64 * row_numel;          // 0 * 64 = 0
for (int64_t base = 0; base < block_numel; ...)    // body never executes
```

No TPUT is issued at all, yet the receive window holds that run's staged input. So on the self slot "the surplus arrived" and "the rank's own staged data was already there" are the same bytes, and the assertion cannot separate them.

I ruled out the obvious mechanism before touching the test. A window-overlap probe (sentinel into window A, read window B, no collective involved) reports **`windows are distinct`** on both sim and NPU — `input_buf` and `data_buf` do not share storage.

The mechanism is therefore still unexplained. It is recorded rather than dropped, and it does not reproduce in sim. No correctness impact is demonstrated: `recv_counts` bounds what any correct consumer reads, and every payload and count assertion passes on both rails. Consistent with it being a property of the HOST staging path — the InCore rail takes its input as a plain `Tensor` rather than through a staged window, and passes the same check on NPU.

Latest commit excludes `src == rank` from that one assertion with the reasoning inline, and softens an overstated claim I had introduced ("window memory is not zero-initialised" → not *guaranteed* zeroed; the probe showed a fresh window reading zero).

Sim re-run after the change: **20/20** on both rails, P=2 and P=4.

### Still outstanding — the actual gate

- [ ] **NPU bandwidth measurement (GO/NO-GO).** Not yet taken; run 1 was correctness only. Target the **InCore** rail; HOST is the cross-check that isolates the answer if they disagree.
- [ ] NPU P=2/P=4 re-run of the two `all_to_all_v` ST files on the corrected test.

Still a draft, and the `perf(...)` prefix is still unearned until there is a number behind it. A NO-GO closes this and #2524 — it would mean TPUT's cost is set by the partition-view descriptor rather than the declared extent, which governs `reduce_scatter` and every future push-based collective.

File: src/ir/op/distributed/collective.cpp [hunk 1]
```diff
@@ -634,9 +634,10 @@ TypePtr DeduceTensorAllToAllVType(const std::vector<ExprPtr>& args,
       << target_dim0->value_ << ")";
 
   // send_counts: per-destination row counts, read at runtime by the lowering
-  // (``tensor.read``) to bound each destination's push loop — this is what
-  // makes the exchange genuinely variable-size rather than a padded transfer
-  // of the full MAX_RECV capacity.  Tensor-like so counts that live in a
+  // (``tensor.read``) and used for two distinct things — it sizes the TPUT
+  // transfer extent (so only the payload crosses the wire, not the full
+  // MAX_RECV capacity) and it is published to the peer as recv_counts (so the
+  // receiver knows which rows are valid).  Tensor-like so counts that live in a
```
[the remark this answers is not in the document]
Comment (georgebisbas) [reply src/ir/op/distributed/collective.cpp:640]: Fixed — the registered `pld.tensor.all_to_all_v` description now documents the runtime `[rows, SIZE]` transfer and the two-sided `[0, MAX_RECV]` clamp (no more "always transfers the full MAX_RECV block" / `min(...)` wording); the lowering-rule header and the in-test comment were corrected to match.

Benchmark experiments (GO/NO-GO gate): the InCore rail ST `tests/st/distributed/collectives/test_l3_tensor_all_to_all_v_intrinsic.py` with `MAX_RECV=32`, `SIZE=64`, and the extreme `send_counts` case (one peer 1 row, the other 32) at P=2, on the free devices 4,5 — baseline `913a5b53` vs branch `eae3b463`. Two measurements: wall-clock (`pytest --durations=10`, n=5, median) and device-side PMU (`enable_pmu=2`, per-task AIV exchange kernel: `pmu_total_cycles`, `mte2_busy_cycles`, `mte3_busy_cycles`). The HOST rail (same ST file and config) was the structural cross-check.

[the remark this answers is not in the document]
Comment (georgebisbas) [reply src/ir/op/distributed/collective.cpp:640]: Fixed — the `REGISTER_OP` description, the lowering-rule header, and the in-test comment now describe the runtime `[rows, SIZE]` transfer with the two-sided clamp and the unwritten tail. The public docs (en/zh) were already accurate on this head.

Benchmark experiments (GO/NO-GO gate): the InCore rail ST `tests/st/distributed/collectives/test_l3_tensor_all_to_all_v_intrinsic.py` with `MAX_RECV=32`, `SIZE=64`, and the extreme `send_counts` case (one peer 1 row, the other 32) at P=2, on the free devices 4,5 — baseline `913a5b53` vs branch `eae3b463`. Two measurements: wall-clock (`pytest --durations=10`, n=5, median) and device-side PMU (`enable_pmu=2`, per-task AIV exchange kernel: `pmu_total_cycles`, `mte2_busy_cycles`, `mte3_busy_cycles`). The HOST rail (same ST file and config) was the structural cross-check.

File: tests/st/distributed/collectives/test_l3_tensor_all_to_all_v_intrinsic.py [hunk 2]
```diff
@@ -207,5 +207,120 @@ def test_all_to_all_v_intrinsic(self, test_config, device_ids, n_ranks):
...
+                # undefined bytes (a fresh window has read zero; a reused one has
+                # read -1.2e+32, 4.2e-41, ...). ``recv_counts`` is what tells the
+                # receiver to ignore them, and it always has.
+                for k in range(n_rows, mr):
+                    would_have_been_sent = inputs[src, rank * mr + k, :]
+                    got_row = outputs[rank, base + k, :]
+                    assert not torch.allclose(got_row, would_have_been_sent, atol=1e-5), (
+                        f"P={nr} case={case} rank={rank} src={src} row={k}: the receiver got the "
+                        f"sender's surplus row — the transfer is not bounded by the runtime count"
+                    )
```
[the remark this answers is not in the document]
Comment (georgebisbas) [reply tests/st/distributed/collectives/test_l3_tensor_all_to_all_v_intrinsic.py:366]: Fixed — the InCore skew ST now copies the full receive window to a `window_out` probe output and asserts the tail against it, so the bounded-transfer check is non-vacuous (a padded full-capacity transfer would now be caught). The HOST check already reads the real window (it failed on NPU on the self slot), where `src == rank` is now excluded. Verified: intrinsic and HOST all_to_all_v STs pass on sim (10/10 each); pre-commit and clang-tidy clean.

Benchmark experiments (GO/NO-GO gate): the InCore rail ST `tests/st/distributed/collectives/test_l3_tensor_all_to_all_v_intrinsic.py` with `MAX_RECV=32`, `SIZE=64`, and the extreme `send_counts` case (one peer 1 row, the other 32) at P=2, on the free devices 4,5 — baseline `913a5b53` vs branch `eae3b463`. Two measurements: wall-clock (`pytest --durations=10`, n=5, median) and device-side PMU (`enable_pmu=2`, per-task AIV exchange kernel: `pmu_total_cycles`, `mte2_busy_cycles`, `mte3_busy_cycles`). The HOST rail (same ST file and config) was the structural cross-check.

**Review by YunjiQin — COMMENTED** [review]
Two review points. The rest of the change looks sound to me — I verified the enabling claims independently: `DeducePutTileType` genuinely does not call `ValidateDynamicTransferHasChunk` (that is `DeducePutType`, tensor-level only), `ValidateStageFitsTransfer` skips the dynamic rows dim while still checking stage cols, `GetDimStrings`/`GetSizeCodes` already emit `?` + `EmitCastToIndex` for dynamic partition-view extents, and the two-sided clamp really is signed end to end (`DataType::INDEX` is outside the `IsUnsignedInt()` range, so `Min`/`Max` lower to `arith.minsi`/`maxsi` and `index_cast` sign-extends) — so both rails agree on a negative `send_counts`.

---

### 1. The user-facing Python docstrings still describe the removed behaviour

The PR updates `docs/en`, `docs/zh`, the registered op description, and the kernel-template comments — but not the two Python layers, which are what a user actually sees from `help(pld.tensor.all_to_all_v)`.

**`python/pypto/language/distributed/op/tensor_ops.py`** (still on the head commit):

```
Each rank pushes a full ``MAX_RECV``-row capacity block to peer ``dest``;
... but they do not change the transfer size.

``MAX_RECV = target.shape[0] // NR`` is both the compile-time per-peer
*capacity* and the fixed transfer size: ... and every push transfers
exactly ``MAX_RECV`` rows regardless of the runtime count.
Rows beyond a sender's count still physically cross the wire ...
```

**`python/pypto/ir/op/distributed/tensor_ops.py`**:

```
returning the target window. Each push transfers a full MAX_RECV-row
capacity block regardless of the runtime count; ...
```

Both paragraphs document exactly the behaviour this PR deletes. `.claude/rules/cross-layer-sync.md` asks for C++ / bindings / Python to move together, and `documentation.md` for docs to follow a behaviour change.

While updating them, please also fold in the second behaviour change — a negative `send_counts[dest]` now publishes `recv_counts = 0` rather than the negative value — since neither docstring mentions it and the `Args` section is where a caller would look.

One thing I would add to the wording in **all** the doc surfaces, not just these two: the tail bytes changed *kind*, not just *value*. Before, the padding rows held the sender's surplus, i.e. finite FP32; now they are uninitialised and can decode as NaN/Inf (the in-test comment already records `-1.2e+32`, `4.2e-41`). A consumer that computes over the dense capacity block and masks by `recv_counts` afterwards — which is the natural MoE-dispatch shape — was correct before and now propagates NaN into valid rows. "Undefined bytes" is accurate but understates that; an explicit "do not do arithmetic over the capacity block before trimming to `recv_counts`" would land better.

---

### 2. See the inline note on the `src == rank` skip in the HOST ST.

File: tests/st/distributed/test_l3_host_tensor_all_to_all_v.py [hunk 3]
```diff
@@ -254,5 +255,116 @@ def test_host_tensor_all_to_all_v(self, test_config, device_ids, n_ranks):
...
+                # send_counts <= 0 the kernel computes block_numel = 0 and the
+                # TPUT loop body never executes, yet the row is present. So on
+                # this slot "surplus arrived" and "local staged data was already
+                # there" are the same bytes, and the check cannot separate them.
+                # It is not evidence of an over-send.
+                #
+                # A window-overlap probe (pypto-3.0-notes issues/mfe/
+                # window_overlap_probe.py) rules out input_buf and data_buf
+                # sharing storage — they are distinct on both sim and NPU — so
+                # the mechanism is still unexplained. Tracked separately; it is
```
Comment (YunjiQin) [inline tests/st/distributed/test_l3_host_tensor_all_to_all_v.py]: This comment points at `pypto-3.0-notes issues/mfe/window_overlap_probe.py`, which is outside this repository — another reader cannot open it, re-run the probe, or judge whether the conclusion still holds. "Tracked separately" also has no number attached.

What is being skipped here is a real, still-unexplained behaviour on the HOST staging path, and the skip is silent: the test reports green with no signal that this slot went unchecked. Could you file it as a GitHub issue and reference the number here instead? A short in-repo summary of what the probe established (the two windows are distinct, so the bytes are locally-staged data rather than an over-send) plus the issue link would make the exclusion auditable.

Related, and worth a line either here or in the InCore ST: the two files are described as the wire-parity gate — same counts, same golden, both rails — but they no longer cover the same `(rank, src)` set, since the InCore side keeps the self slot. Worth making that asymmetry explicit where the claim is made, or expressing it as an `xfail` so the uncovered path stays visible in the test report rather than disappearing into a `continue`.

Comment (georgebisbas) [reply tests/st/distributed/test_l3_host_tensor_all_to_all_v.py]: Filed as **#2546** — the comment now cites it and carries a short in-repo summary, so the exclusion is auditable without leaving the repository. The issue has the `block_numel = 0` proof that it cannot be an over-send, the probe source and its result on both platforms, an explicit "no correctness impact demonstrated" note, and a suggested next step (dump the resolved `input_buf` / `data_buf` / `CommRemotePtr(..., dest == my_rank)` addresses on NPU).

You were right that the reference was unusable — `pypto-3.0-notes` is a separate repository, so nobody reviewing this could open it or re-run the probe.

On the parity point: also correct, and I have made the asymmetry explicit in **both** class docstrings rather than only where the claim was made, since a reader could start from either file. Parity now reads as: payload rows and `recv_counts` are checked for every `(rank, src)` pair on both rails; the tail is checked for every pair *except* HOST self.

I did not convert it to `xfail`, and I would rather say why than leave it looking like an oversight. The exclusion is one iteration of a `for src in range(nr)` loop inside a test that otherwise passes, so pytest has no per-slot outcome to mark — surfacing it as its own report line would mean splitting the parametrisation per `(rank, src)`. That is a real option if you would prefer the uncovered slot to be visible in the test report; it costs `nr²` test cases per case×rank-count, so I left it as an explicit docstring statement plus the issue link. Happy to switch if you would rather have the report line.

Fixed in `21c8c9bd`.

**Comment by georgebisbas** [comment]
Thanks — both findings were valid, and I verified each against the branch head rather than taking them on trust. Addressed in `21c8c9bd`.

## 1. Stale Python docstrings — confirmed and fixed

Confirmed before fixing: 2 stale phrases in each file, and **neither had been touched by this PR**. A clean `cross-layer-sync.md` miss on my part — I updated `docs/en`, `docs/zh`, the registered op description and the kernel comments, and stopped at exactly the layer a user actually reads.

- `language/distributed/op/tensor_ops.py` claimed `MAX_RECV` was *"both the compile-time per-peer capacity and the fixed transfer size"* and that surplus rows *"still physically cross the wire"*.
- `ir/op/distributed/tensor_ops.py` said each push transfers *"a full MAX_RECV-row capacity block regardless of the runtime count"*.

Both now describe the runtime `[rows, SIZE]` extent and the two-sided clamp, and both fold in the second behaviour change — a negative `send_counts[dest]` publishes `recv_counts = 0` — including in the `Args` entry for `recv_counts`, which is where a caller would look for it. Verified no stale phrasing survives anywhere in `python/`, `src/` or `docs/`.

## 2. The tail changed *kind*, not just value — this was the important one

You are right, and "undefined bytes" understated it to the point of being misleading. The distinction I had missed: the old full-capacity push left the sender's surplus there, which was **always finite FP32**. Uninitialised memory is not, and a consumer that reduces over the dense `[NR*MAX_RECV, SIZE]` block and masks by `recv_counts` afterwards — the natural MoE-dispatch shape, and the workload that motivated this change — was correct before and would now pull NaN into otherwise-valid rows.

So this is closer to a silent numerical hazard than a documentation nicety, and I had it filed under the latter. It now carries an explicit *"trim to `recv_counts` before doing arithmetic over the capacity block; mask first, then compute"* across **five** surfaces rather than the two you named — `docs/en`, `docs/zh`, the `REGISTER_OP` description, the kernel-template comment, and both Python docstrings — since a reader can arrive at any of them.

## 3. Inline point

Replied on the thread: filed as #2546, comment now cites it, and the wire-parity asymmetry is stated explicitly in both ST class docstrings.

## Verification

`all_to_all_v` UTs 7/7; both ST files 20/20 on `a2a3sim` at P=2 and P=4; `pre-commit` clean.

One caveat on that, since it nearly went the other way: my first rebuild silently reused a stale `.so` — `pip install --target` warns rather than overwriting, and the warning scrolls past above a green summary, so the tests passed against yesterday's binary. The numbers above come from a rebuild where the built `.so` was checked for the new string before the tests ran.

**Review by YunjiQin — APPROVED** [review]
